name: Daily Commit

on:
  schedule:
    - cron: '52 11 * * *'  # Runs every day at midnight UTC

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make a dummy change
      run: |
        echo "Last run at $(date)" > last-run.txt
        git config --global user.email "v.g7404@gmail.com"
        git config --global user.name "ivarungupta"
        git add last-run.txt
        git commit -m "Automated commit xyz"

    - name: Push changes
      run: git push
