name: Daily Commit

on:
  schedule:
    - cron: '57 11 * * *'  # Runs daily at 11:50 UTC (17:20 IST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make a dummy change
      run: |
        echo "Last run at $(date)" > last-run.txt
        git config --global user.email "v.g7404@gmail.com"
        git config --global user.name "ivarungupta"
        git add last-run.txt
        git commit -m "Automated commit to maintain streak"

    - name: Push changes
      run: git push
